const productsData = {
    "moringa-leaf-powder": {
        "name": "Moringa Leaf Powder",
        "tagline": "Rich in Antioxidants & Plant Protein",
        "description": "Our organic Moringa Leaf Powder is sourced from the finest Moringa trees in India. Known as a 'miracle tree', Moringa is packed with essential vitamins, minerals, and plant-based protein. This nutrient-dense superfood is perfect for boosting energy, supporting immunity, and enhancing overall vitality.",
        "price": "$12.00",
        "originalPrice": "$15.00",
        "save": "20%",
        "images": ["images/Moringa-Leaf-Powder.jpg", "images/product-thumb-4.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-MOR-001",
        "origin": "India",
        "moq": "500 kg"
    },
    "lakadong-turmeric": {
        "name": "Lakadong Turmeric",
        "tagline": "Ancient Immunity Booster",
        "description": "Grown in the Lakadong region of Meghalaya, this turmeric is famous for its exceptionally high curcumin content (7-12%). Our Lakadong Turmeric is hand-picked and processed using traditional methods to preserve its potent anti-inflammatory and antioxidant properties.",
        "price": "$18.00",
        "originalPrice": "$22.00",
        "save": "18%",
        "images": ["images/Lakadong-Haldi.jpg", "images/product-thumb-1.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-TUR-002",
        "origin": "India",
        "moq": "1000 kg"
    },
    "raw-forest-honey": {
        "name": "Raw Forest Honey",
        "tagline": "Unprocessed & Wild Harvested",
        "description": "Our Raw Forest Honey is collected by traditional honey hunters from the deep forests of India. It is 100% natural, unprocessed, and free from any additives. Rich in enzymes and antioxidants, this honey carries the unique floral essence of the wild.",
        "price": "$15.00",
        "originalPrice": "$18.00",
        "save": "16%",
        "images": ["images/Raw-Forest-Honey.jpg", "images/product-thumb-9.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-HON-003",
        "origin": "India",
        "moq": "250 kg"
    },
    "raw-banana-powder": {
        "name": "Raw Banana Powder",
        "tagline": "Gut Friendly & Baby Nutrition",
        "description": "Made from high-quality raw green bananas, this powder is a powerhouse of resistant starch and prebiotic fiber. It's an excellent gluten-free flour alternative and a highly nutritious supplement for infants and health-conscious adults alike.",
        "price": "$10.00",
        "originalPrice": "$12.00",
        "save": "16%",
        "images": ["images/Raw-Banana-Powder.jpg", "images/product-thumb-5.png"],
        "category": "Functional Flours",
        "sku": "AYU-BAN-004",
        "origin": "India",
        "moq": "300 kg"
    },
    "sattu-roasted-gram-flour": {
        "name": "Sattu (Roasted Gram Flour)",
        "tagline": "The Indian Protein",
        "description": "Sattu is a traditional Indian 'superfood' made by stone-grinding roasted Bengal grams. It's exceptionally high in protein and insoluble fiber, making it an ideal pre-workout drink or a nutritious addition to various culinary preparations.",
        "price": "$8.00",
        "originalPrice": "$10.00",
        "save": "20%",
        "images": ["images/Sattu-Roasted-Gram-Flour.jpg", "images/product-thumb-2.png"],
        "category": "Functional Flours",
        "sku": "AYU-SAT-005",
        "origin": "India",
        "moq": "500 kg"
    },
    "ragi-finger-millet-flour": {
        "name": "Ragi (Finger Millet) Flour",
        "tagline": "High Calcium Superfood",
        "description": "Ragi is one of the most nutritious millets, naturally rich in calcium, iron, and amino acids. Our stone-ground Ragi flour is perfect for gluten-free baking and preparing healthy traditional porridges.",
        "price": "$7.00",
        "originalPrice": "$9.00",
        "save": "22%",
        "images": ["images/Ragi-Finger-Millet-Flour.jpg", "images/product-thumb-3.png"],
        "category": "Functional Flours",
        "sku": "AYU-RAG-006",
        "origin": "India",
        "moq": "500 kg"
    },
    "sesame-seeds": {
        "name": "Sesame Oil (Black & White)",
        "tagline": "Cold Pressed & Unrefined",
        "description": "Our premium Sesame Oil is cold-pressed to retain its natural nutrients and distinct nutty aroma. It's a versatile oil for cooking and traditional wellness practices, rich in antioxidants and healthy fats.",
        "price": "$9.00",
        "originalPrice": "$11.00",
        "save": "18%",
        "images": ["images/Sesame-Seeds.jpg", "images/product-thumb-6.png"],
        "category": "Seeds & Healthy Fats",
        "sku": "AYU-SES-007",
        "origin": "India",
        "moq": "1000 kg"
    },
    "sabja-basil-seeds": {
        "name": "Sabja (Basil) Seeds",
        "tagline": "Cooling & Digestive Superfood",
        "description": "Sabja seeds are a traditional cooling agent in Ayurveda. When soaked, they swell to form a gelatinous texture, perfect for drinks and desserts. They are rich in fiber and help in maintaining digestive health.",
        "price": "$5.00",
        "originalPrice": "$6.00",
        "save": "16%",
        "images": ["images/Sabja-Seeds.jpg", "images/product-thumb-7.png"],
        "category": "Seeds & Healthy Fats",
        "sku": "AYU-SAB-008",
        "origin": "India",
        "moq": "500 kg"
    },
    "flaxseeds-alsi": {
        "name": "Flaxseeds (Alsi)",
        "tagline": "Rich in Omega-3",
        "description": "Our organic Flaxseeds are a superior plant-based source of Omega-3 fatty acids and lignans. They can be ground and added to smoothies, baked goods, or cereals to boost fiber and heart-healthy fat intake.",
        "price": "$6.00",
        "originalPrice": "$8.00",
        "save": "25%",
        "images": ["images/Flaxseeds.jpg", "images/product-thumb-8.png"],
        "category": "Seeds & Healthy Fats",
        "sku": "AYU-FLX-009",
        "origin": "India",
        "moq": "500 kg"
    },
    "pumpkin-seeds": {
        "name": "Pumpkin Seeds",
        "tagline": "Zinc & Magnesium Rich",
        "description": "Organic Pumpkin Seeds are a delicious and nutritious snack. They are particularly high in zinc and magnesium, supporting immune function and heart health. Perfect as a topper for salads and soups.",
        "price": "$11.00",
        "originalPrice": "$14.00",
        "save": "21%",
        "images": ["images/Pumpkin-Seeds.jpg", "images/product-thumb-10.png"],
        "category": "Seeds & Healthy Fats",
        "sku": "AYU-PUM-010",
        "origin": "India",
        "moq": "2000 kg"
    },
    "amla-powder": {
        "name": "Amla Powder",
        "tagline": "Highest Natural Vitamin C",
        "description": "Amla (Indian Gooseberry) is revered in Ayurveda for its exceptional Vitamin C content and rejuvenating properties. Our Amla Powder supports immune health, hair growth, and radiant skin.",
        "price": "$9.00",
        "originalPrice": "$12.00",
        "save": "25%",
        "images": ["images/Amla-Powder.jpg", "images/product-thumb-11.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-AML-011",
        "origin": "India",
        "moq": "500 kg"
    },
    "ashwagandha-powder": {
        "name": "Ashwagandha Powder",
        "tagline": "Adaptogen for Stress & Energy",
        "description": "Ashwagandha is one of the most powerful herbs in Ayurvedic healing. Our organic Ashwagandha Root Powder helps the body manage stress, boosts energy levels, and improves concentration and sleep quality.",
        "price": "$14.00",
        "originalPrice": "$18.00",
        "save": "22%",
        "images": ["images/Ashwagandha-Powder.jpg", "images/product-thumb-12.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-ASH-012",
        "origin": "India",
        "moq": "300 kg"
    },
    "wheatgrass-powder": {
        "name": "Wheatgrass Powder",
        "tagline": "Pure Detox & Daily Greens",
        "description": "Our Wheatgrass Powder is made from the vibrant young shoots of the wheat plant. It's a chlorophyll-rich detoxifier that provides a concentrated dose of vitamins, minerals, and antioxidants for daily wellness.",
        "price": "$13.00",
        "originalPrice": "$16.00",
        "save": "19%",
        "images": ["images/Wheatgrass-Powder.jpg", "images/product-thumb-13.png"],
        "category": "Immunity & Vitality",
        "sku": "AYU-WHT-013",
        "origin": "India",
        "moq": "500 kg"
    },
    "amaranth-flour": {
        "name": "Amaranth Flour",
        "tagline": "Gluten-Free Super Flour",
        "description": "Amaranth is an ancient grain naturally high in protein and lysine. Our gluten-free Amaranth Flour is excellent for thickening sauces, making rotis, or as a nutritious ingredient in baking.",
        "price": "$8.00",
        "originalPrice": "$10.00",
        "save": "20%",
        "images": ["images/Amaranth-Flour.jpg", "images/product-thumb-14.png"],
        "category": "Functional Flours",
        "sku": "AYU-AMA-014",
        "origin": "India",
        "moq": "500 kg"
    },
    "wood-pressed-sesame-oil": {
        "name": "Wood-Pressed Sesame Oil",
        "tagline": "Cold Pressed & Unrefined",
        "description": "Extracted using traditional wooden 'ghani' machines, this oil retains all its natural nutrients, flavor, and essence. A premium oil for both culinary and Ayurvedic self-massage (Abhyanga).",
        "price": "$11.00",
        "originalPrice": "$14.00",
        "save": "21%",
        "images": ["images/Wood-Pressed-Sesame-Oil.jpg", "images/product-thumb-15.png"],
        "category": "Seeds & Healthy Fats",
        "sku": "AYU-WPS-015",
        "origin": "India",
        "moq": "1000 kg"
    },
    "phool-makhana": {
        "name": "Phool Makhana",
        "tagline": "Raw & Roasted with Olive Oil",
        "description": "Also known as Fox Nuts or Lotus Seeds, Phool Makhana is an incredibly light and healthy snack. It's low in cholesterol, fat, and sodium, making it a perfect weight-loss-friendly snack.",
        "price": "$10.00",
        "originalPrice": "$13.00",
        "save": "23%",
        "images": ["images/Phool-Makhana.jpg", "images/product-thumb-16.png"],
        "category": "Wellness Snacks",
        "sku": "AYU-MAK-016",
        "origin": "India",
        "moq": "500 kg"
    },
    "roasted-chana": {
        "name": "Roasted Chana",
        "tagline": "Ancient Organic & Sustainable Living",
        "description": "Our Roasted Chana (Bengal Gram) is a crunchy, high-protein snack. Sustainably grown and dry-roasted to perfection, it's a nostalgic healthy snack that keeps you full for longer.",
        "price": "$6.00",
        "originalPrice": "$8.00",
        "save": "25%",
        "images": ["images/Roasted-Chana.jpg", "images/product-thumb-17.png"],
        "category": "Wellness Snacks",
        "sku": "AYU-CHA-017",
        "origin": "India",
        "moq": "1000 kg"
    },
    "millet-puffs": {
        "name": "Millet Puffs",
        "tagline": "Light, Airy & Delicious",
        "description": "Millet Puffs are the perfect guilt-free snack. Made from ancient millets, they are gluten-free, low in calories, and high in fiber. A great base for healthy 'bhel' or enjoyed plain.",
        "price": "$7.00",
        "originalPrice": "$9.00",
        "save": "22%",
        "images": ["images/Millet-Puffs.jpg", "images/product-thumb-18.png"],
        "category": "Wellness Snacks",
        "sku": "AYU-MIL-018",
        "origin": "India",
        "moq": "500 kg"
    },
    "jaggery-powder": {
        "name": "Jaggery Powder",
        "tagline": "Natural Sugar Alternative",
        "description": "Our organic Jaggery Powder is made from the juice of hand-harvested sugarcane. It is a healthy alternative to white sugar, rich in minerals like iron and magnesium, and provides a sustained energy release.",
        "price": "$6.00",
        "originalPrice": "$8.00",
        "save": "25%",
        "images": ["images/Jaggery-Powder.jpg", "images/product-thumb-19.png"],
        "category": "Natural Sweeteners",
        "sku": "AYU-JAG-019",
        "origin": "India",
        "moq": "500 kg"
    },
    "palm-jaggery": {
        "name": "Palm Jaggery",
        "tagline": "Natural Sweetener & Ayurvedic",
        "description": "Palm Jaggery (Karupatti) is a nutrient-rich sweetener made from the extract of palm trees. It has a low glycemic index and is packed with iron and other essential minerals, making it highly valued in Ayurveda.",
        "price": "$9.00",
        "originalPrice": "$12.00",
        "save": "25%",
        "images": ["images/Palm-Jaggery.jpg", "images/product-thumb-20.png"],
        "category": "Natural Sweeteners",
        "sku": "AYU-PAL-020",
        "origin": "India",
        "moq": "500 kg"
    },
    "stevia-leaves": {
        "name": "Stevia Leaves",
        "tagline": "Zero Calorie & Natural Sweetener",
        "description": "Our organic Stevia Leaves are a 100% natural, zero-calorie sweetener. Perfect for diabetics and those looking to reduce sugar intake without sacrificing sweetness. Use in teas, coffees, and desserts.",
        "price": "$12.00",
        "originalPrice": "$15.00",
        "save": "20%",
        "images": ["images/Stevia-Leaves.jpg", "images/product-thumb-21.png"],
        "category": "Natural Sweeteners",
        "sku": "AYU-STE-021",
        "origin": "India",
        "moq": "300 kg"
    }
};
